/* The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
 The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?*/

package projectEuler;

public class Problem12 {
	
	public static void main(String[] args) {
		long i,j;
		long num=0;
		int count;
		
		for(i=1;i<1000000000;i++){
			num=num+i;
			count=0;
			for(j=1;j*j<=num;j++){	// for loop will only go up to the square root of the number.		
				if((num%j)==0){
					count=count+2; // add up by two every time instead of one. 
					               // because it will only count upto the sqaure root of the number.
					}
				}
				if(count>500){
					System.out.println(num);
					break; }
				} 
		}	
}
	